# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
    - uses: astral-sh/ruff-action@v3
      with:
        args: "format --check --diff"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.5"
    - name: Install scabha
      run: uv sync --group tests
    - name: Test with pytest
      run: uv run pytest tests
    # After such much drama and heated debate (PR #32), @o-smirnov
    # prevailed upon the young purists to add the tests below. Yes it
    # seems backwards, but this is a pragmatic measure to quickly catch
    # stimela-breaking changes.
    # @SpheMakh and @JSKenyon are on the record as being against this,
    # so if this addition causes kak down the road, we can back it out
    # and @o-smirnov must mollify the youngsters with beers.
    - name: Checkout stimela master
      uses: actions/checkout@v4
      with:
        repository: caracal-pipeline/stimela
        path: stimela
    - name: Install stimela from master
      run: |
        uv pip install -e stimela
        uv pip install -e .
    - name: Test stimela with pytest
      run: uv run pytest stimela/tests
